<?php

/**
 * Référentiel pays (ISO 3166-1) — source unique pour la saisie du pays d'un
 * client et pour l'analytique des marchés émetteurs.
 *
 * Format : 'ALPHA2' => [nom français, continent, code ISO numérique]
 *
 * Le code numérique sert à joindre les données au fond de carte world-atlas
 * (dont les identifiants de pays sont les codes ISO numériques) pour le rendu
 * de la carte choroplèthe côté console business.
 *
 * Il est volontairement stocké en entier sans zéro initial : en PHP, un
 * littéral « 012 » serait interprété en octal.
 */
return [
    // ── Afrique ───────────────────────────────────────────────────────────
    'DZ' => ['Algérie', 'Afrique', 12],
    'AO' => ['Angola', 'Afrique', 24],
    'BJ' => ['Bénin', 'Afrique', 204],
    'BW' => ['Botswana', 'Afrique', 72],
    'BF' => ['Burkina Faso', 'Afrique', 854],
    'BI' => ['Burundi', 'Afrique', 108],
    'CM' => ['Cameroun', 'Afrique', 120],
    'CV' => ['Cap-Vert', 'Afrique', 132],
    'CF' => ['République centrafricaine', 'Afrique', 140],
    'TD' => ['Tchad', 'Afrique', 148],
    'KM' => ['Comores', 'Afrique', 174],
    'CG' => ['Congo', 'Afrique', 178],
    'CD' => ['République démocratique du Congo', 'Afrique', 180],
    'CI' => ['Côte d’Ivoire', 'Afrique', 384],
    'DJ' => ['Djibouti', 'Afrique', 262],
    'EG' => ['Égypte', 'Afrique', 818],
    'GQ' => ['Guinée équatoriale', 'Afrique', 226],
    'ER' => ['Érythrée', 'Afrique', 232],
    'SZ' => ['Eswatini', 'Afrique', 748],
    'ET' => ['Éthiopie', 'Afrique', 231],
    'GA' => ['Gabon', 'Afrique', 266],
    'GM' => ['Gambie', 'Afrique', 270],
    'GH' => ['Ghana', 'Afrique', 288],
    'GN' => ['Guinée', 'Afrique', 324],
    'GW' => ['Guinée-Bissau', 'Afrique', 624],
    'KE' => ['Kenya', 'Afrique', 404],
    'LS' => ['Lesotho', 'Afrique', 426],
    'LR' => ['Libéria', 'Afrique', 430],
    'LY' => ['Libye', 'Afrique', 434],
    'MG' => ['Madagascar', 'Afrique', 450],
    'MW' => ['Malawi', 'Afrique', 454],
    'ML' => ['Mali', 'Afrique', 466],
    'MR' => ['Mauritanie', 'Afrique', 478],
    'MU' => ['Maurice', 'Afrique', 480],
    'MA' => ['Maroc', 'Afrique', 504],
    'MZ' => ['Mozambique', 'Afrique', 508],
    'NA' => ['Namibie', 'Afrique', 516],
    'NE' => ['Niger', 'Afrique', 562],
    'NG' => ['Nigéria', 'Afrique', 566],
    'RW' => ['Rwanda', 'Afrique', 646],
    'RE' => ['Réunion', 'Afrique', 638],
    'ST' => ['Sao Tomé-et-Principe', 'Afrique', 678],
    'SN' => ['Sénégal', 'Afrique', 686],
    'SC' => ['Seychelles', 'Afrique', 690],
    'SL' => ['Sierra Leone', 'Afrique', 694],
    'SO' => ['Somalie', 'Afrique', 706],
    'ZA' => ['Afrique du Sud', 'Afrique', 710],
    'SS' => ['Soudan du Sud', 'Afrique', 728],
    'SD' => ['Soudan', 'Afrique', 729],
    'TZ' => ['Tanzanie', 'Afrique', 834],
    'TG' => ['Togo', 'Afrique', 768],
    'TN' => ['Tunisie', 'Afrique', 788],
    'UG' => ['Ouganda', 'Afrique', 800],
    'YT' => ['Mayotte', 'Afrique', 175],
    'ZM' => ['Zambie', 'Afrique', 894],
    'ZW' => ['Zimbabwe', 'Afrique', 716],

    // ── Europe ────────────────────────────────────────────────────────────
    'AL' => ['Albanie', 'Europe', 8],
    'DE' => ['Allemagne', 'Europe', 276],
    'AD' => ['Andorre', 'Europe', 20],
    'AT' => ['Autriche', 'Europe', 40],
    'BE' => ['Belgique', 'Europe', 56],
    'BY' => ['Biélorussie', 'Europe', 112],
    'BA' => ['Bosnie-Herzégovine', 'Europe', 70],
    'BG' => ['Bulgarie', 'Europe', 100],
    'CY' => ['Chypre', 'Europe', 196],
    'HR' => ['Croatie', 'Europe', 191],
    'DK' => ['Danemark', 'Europe', 208],
    'ES' => ['Espagne', 'Europe', 724],
    'EE' => ['Estonie', 'Europe', 233],
    'FI' => ['Finlande', 'Europe', 246],
    'FR' => ['France', 'Europe', 250],
    'GR' => ['Grèce', 'Europe', 300],
    'HU' => ['Hongrie', 'Europe', 348],
    'IE' => ['Irlande', 'Europe', 372],
    'IS' => ['Islande', 'Europe', 352],
    'IT' => ['Italie', 'Europe', 380],
    'LV' => ['Lettonie', 'Europe', 428],
    'LI' => ['Liechtenstein', 'Europe', 438],
    'LT' => ['Lituanie', 'Europe', 440],
    'LU' => ['Luxembourg', 'Europe', 442],
    'MK' => ['Macédoine du Nord', 'Europe', 807],
    'MT' => ['Malte', 'Europe', 470],
    'MD' => ['Moldavie', 'Europe', 498],
    'MC' => ['Monaco', 'Europe', 492],
    'ME' => ['Monténégro', 'Europe', 499],
    'NO' => ['Norvège', 'Europe', 578],
    'NL' => ['Pays-Bas', 'Europe', 528],
    'PL' => ['Pologne', 'Europe', 616],
    'PT' => ['Portugal', 'Europe', 620],
    'RO' => ['Roumanie', 'Europe', 642],
    'GB' => ['Royaume-Uni', 'Europe', 826],
    'RU' => ['Russie', 'Europe', 643],
    'SM' => ['Saint-Marin', 'Europe', 674],
    'RS' => ['Serbie', 'Europe', 688],
    'SK' => ['Slovaquie', 'Europe', 703],
    'SI' => ['Slovénie', 'Europe', 705],
    'SE' => ['Suède', 'Europe', 752],
    'CH' => ['Suisse', 'Europe', 756],
    'CZ' => ['Tchéquie', 'Europe', 203],
    'UA' => ['Ukraine', 'Europe', 804],
    'VA' => ['Vatican', 'Europe', 336],

    // ── Asie ──────────────────────────────────────────────────────────────
    'AF' => ['Afghanistan', 'Asie', 4],
    'SA' => ['Arabie saoudite', 'Asie', 682],
    'AM' => ['Arménie', 'Asie', 51],
    'AZ' => ['Azerbaïdjan', 'Asie', 31],
    'BH' => ['Bahreïn', 'Asie', 48],
    'BD' => ['Bangladesh', 'Asie', 50],
    'BT' => ['Bhoutan', 'Asie', 64],
    'MM' => ['Birmanie', 'Asie', 104],
    'BN' => ['Brunei', 'Asie', 96],
    'KH' => ['Cambodge', 'Asie', 116],
    'CN' => ['Chine', 'Asie', 156],
    'KR' => ['Corée du Sud', 'Asie', 410],
    'KP' => ['Corée du Nord', 'Asie', 408],
    'AE' => ['Émirats arabes unis', 'Asie', 784],
    'GE' => ['Géorgie', 'Asie', 268],
    'HK' => ['Hong Kong', 'Asie', 344],
    'IN' => ['Inde', 'Asie', 356],
    'ID' => ['Indonésie', 'Asie', 360],
    'IQ' => ['Irak', 'Asie', 368],
    'IR' => ['Iran', 'Asie', 364],
    'IL' => ['Israël', 'Asie', 376],
    'JP' => ['Japon', 'Asie', 392],
    'JO' => ['Jordanie', 'Asie', 400],
    'KZ' => ['Kazakhstan', 'Asie', 398],
    'KG' => ['Kirghizistan', 'Asie', 417],
    'KW' => ['Koweït', 'Asie', 414],
    'LA' => ['Laos', 'Asie', 418],
    'LB' => ['Liban', 'Asie', 422],
    'MO' => ['Macao', 'Asie', 446],
    'MY' => ['Malaisie', 'Asie', 458],
    'MV' => ['Maldives', 'Asie', 462],
    'MN' => ['Mongolie', 'Asie', 496],
    'NP' => ['Népal', 'Asie', 524],
    'OM' => ['Oman', 'Asie', 512],
    'UZ' => ['Ouzbékistan', 'Asie', 860],
    'PK' => ['Pakistan', 'Asie', 586],
    'PS' => ['Palestine', 'Asie', 275],
    'PH' => ['Philippines', 'Asie', 608],
    'QA' => ['Qatar', 'Asie', 634],
    'SG' => ['Singapour', 'Asie', 702],
    'LK' => ['Sri Lanka', 'Asie', 144],
    'SY' => ['Syrie', 'Asie', 760],
    'TJ' => ['Tadjikistan', 'Asie', 762],
    'TW' => ['Taïwan', 'Asie', 158],
    'TH' => ['Thaïlande', 'Asie', 764],
    'TL' => ['Timor oriental', 'Asie', 626],
    'TM' => ['Turkménistan', 'Asie', 795],
    'TR' => ['Turquie', 'Asie', 792],
    'VN' => ['Viêt Nam', 'Asie', 704],
    'YE' => ['Yémen', 'Asie', 887],

    // ── Amériques ─────────────────────────────────────────────────────────
    'AG' => ['Antigua-et-Barbuda', 'Amériques', 28],
    'AR' => ['Argentine', 'Amériques', 32],
    'BS' => ['Bahamas', 'Amériques', 44],
    'BB' => ['Barbade', 'Amériques', 52],
    'BZ' => ['Belize', 'Amériques', 84],
    'BO' => ['Bolivie', 'Amériques', 68],
    'BR' => ['Brésil', 'Amériques', 76],
    'CA' => ['Canada', 'Amériques', 124],
    'CL' => ['Chili', 'Amériques', 152],
    'CO' => ['Colombie', 'Amériques', 170],
    'CR' => ['Costa Rica', 'Amériques', 188],
    'CU' => ['Cuba', 'Amériques', 192],
    'DM' => ['Dominique', 'Amériques', 212],
    'SV' => ['Salvador', 'Amériques', 222],
    'EC' => ['Équateur', 'Amériques', 218],
    'US' => ['États-Unis', 'Amériques', 840],
    'GD' => ['Grenade', 'Amériques', 308],
    'GP' => ['Guadeloupe', 'Amériques', 312],
    'GT' => ['Guatemala', 'Amériques', 320],
    'GF' => ['Guyane française', 'Amériques', 254],
    'GY' => ['Guyana', 'Amériques', 328],
    'HT' => ['Haïti', 'Amériques', 332],
    'HN' => ['Honduras', 'Amériques', 340],
    'JM' => ['Jamaïque', 'Amériques', 388],
    'MQ' => ['Martinique', 'Amériques', 474],
    'MX' => ['Mexique', 'Amériques', 484],
    'NI' => ['Nicaragua', 'Amériques', 558],
    'PA' => ['Panama', 'Amériques', 591],
    'PY' => ['Paraguay', 'Amériques', 600],
    'PE' => ['Pérou', 'Amériques', 604],
    'PR' => ['Porto Rico', 'Amériques', 630],
    'DO' => ['République dominicaine', 'Amériques', 214],
    'KN' => ['Saint-Kitts-et-Nevis', 'Amériques', 659],
    'LC' => ['Sainte-Lucie', 'Amériques', 662],
    'VC' => ['Saint-Vincent-et-les-Grenadines', 'Amériques', 670],
    'SR' => ['Suriname', 'Amériques', 740],
    'TT' => ['Trinité-et-Tobago', 'Amériques', 780],
    'UY' => ['Uruguay', 'Amériques', 858],
    'VE' => ['Venezuela', 'Amériques', 862],

    // ── Océanie ───────────────────────────────────────────────────────────
    'AU' => ['Australie', 'Océanie', 36],
    'FJ' => ['Fidji', 'Océanie', 242],
    'KI' => ['Kiribati', 'Océanie', 296],
    'MH' => ['Îles Marshall', 'Océanie', 584],
    'SB' => ['Îles Salomon', 'Océanie', 90],
    'FM' => ['Micronésie', 'Océanie', 583],
    'NR' => ['Nauru', 'Océanie', 520],
    'NC' => ['Nouvelle-Calédonie', 'Océanie', 540],
    'NZ' => ['Nouvelle-Zélande', 'Océanie', 554],
    'PW' => ['Palaos', 'Océanie', 585],
    'PG' => ['Papouasie-Nouvelle-Guinée', 'Océanie', 598],
    'PF' => ['Polynésie française', 'Océanie', 258],
    'WS' => ['Samoa', 'Océanie', 882],
    'TO' => ['Tonga', 'Océanie', 776],
    'TV' => ['Tuvalu', 'Océanie', 798],
    'VU' => ['Vanuatu', 'Océanie', 548],
];
